# Generated by Django 4.2 on 2024-06-28 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promise',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='promise',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BrokenPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise.promise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'promise')},
            },
        ),
    ]
