# Generated by Django 4.2 on 2024-06-29 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0002_alter_promise_options_alter_promise_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='status',
            field=models.CharField(choices=[('not start', 'NOT START'), ('in progress', 'IN PROGRESS'), ('finished', 'FINISHED'), ('failed', 'FAILED')], default='not start', max_length=12),
        ),
        migrations.CreateModel(
            name='FinishedPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.TextField()),
                ('href', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now=True)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise.promise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'promise')},
            },
        ),
    ]
