# Generated by Django 4.2 on 2024-07-01 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0003_alter_promise_status_finishedpromise'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise.promise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promise Commit',
                'verbose_name_plural': 'Promise Commits',
                'ordering': ['-created_at'],
            },
        ),
    ]
