# Generated by Django 4.2 on 2024-07-01 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0005_liketopromise_disliketobook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DislikeToBook',
            new_name='DislikeToPromise',
        ),
    ]
